/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as MatchupsRouteImport } from './routes/matchups'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerPlayerIdRouteImport } from './routes/player.$playerId'

const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchupsRoute = MatchupsRouteImport.update({
  id: '/matchups',
  path: '/matchups',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerPlayerIdRoute = PlayerPlayerIdRouteImport.update({
  id: '/player/$playerId',
  path: '/player/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/events': typeof EventsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/matchups': typeof MatchupsRoute
  '/my-events': typeof MyEventsRoute
  '/score': typeof ScoreRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/events': typeof EventsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/matchups': typeof MatchupsRoute
  '/my-events': typeof MyEventsRoute
  '/score': typeof ScoreRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/events': typeof EventsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/matchups': typeof MatchupsRoute
  '/my-events': typeof MyEventsRoute
  '/score': typeof ScoreRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/events'
    | '/leaderboard'
    | '/login'
    | '/matchups'
    | '/my-events'
    | '/score'
    | '/player/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/events'
    | '/leaderboard'
    | '/login'
    | '/matchups'
    | '/my-events'
    | '/score'
    | '/player/$playerId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/events'
    | '/leaderboard'
    | '/login'
    | '/matchups'
    | '/my-events'
    | '/score'
    | '/player/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EventsRoute: typeof EventsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MatchupsRoute: typeof MatchupsRoute
  MyEventsRoute: typeof MyEventsRoute
  ScoreRoute: typeof ScoreRoute
  PlayerPlayerIdRoute: typeof PlayerPlayerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchups': {
      id: '/matchups'
      path: '/matchups'
      fullPath: '/matchups'
      preLoaderRoute: typeof MatchupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$playerId': {
      id: '/player/$playerId'
      path: '/player/$playerId'
      fullPath: '/player/$playerId'
      preLoaderRoute: typeof PlayerPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EventsRoute: EventsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MatchupsRoute: MatchupsRoute,
  MyEventsRoute: MyEventsRoute,
  ScoreRoute: ScoreRoute,
  PlayerPlayerIdRoute: PlayerPlayerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
